import java.util.*;
import ghidra.app.script.GhidraScript;
import ghidra.app.services.DataTypeManagerService;
import ghidra.framework.plugintool.PluginTool;
import ghidra.program.model.data.*;
import ghidra.program.model.listing.*;
import ghidra.program.model.address.*;
import ghidra.program.model.symbol.*;
import ghidra.program.model.listing.Function.FunctionUpdateType;

public class df_ghidra extends GhidraScript {

    DataTypeManager manager;
    Address vmeth_nullptr;

    void applyFunctionType(Address addr, String fnName, FunctionDefinition fnDataType, DataType thisType) throws Exception
    {
        Function fn = getFunctionAt(addr);
        if (fn == null)
            fn = createFunction(addr, fnName);

        fn.setName(fnName, SourceType.USER_DEFINED);

        fn.setCallingConvention("__fastcall");
        fn.setReturnType(fnDataType.getReturnType(), SourceType.USER_DEFINED);

        List params = new ArrayList();
        ParameterDefinition[] typeParams = fnDataType.getArguments();
        for (int i = 0; i < typeParams.length; i++)
        {
            ParameterDefinition p = typeParams[i];
            DataType t = "this".equals(p.getName()) ? thisType : p.getDataType();
            params.add(new ParameterImpl(p.getName(), t, currentProgram));
        }
        fn.replaceParameters(params, FunctionUpdateType.DYNAMIC_STORAGE_ALL_PARAMS, true, SourceType.USER_DEFINED);
    }

    void applyVmethodType(Address vtableAddr, int pos, String className, String fnName, FunctionDefinition fnDataType, Address parentVtableAddr) throws Exception
    {
        Data d = getDataAt(vtableAddr).getComponent(pos);

        if (d.getValue().equals(vmeth_nullptr))
            return;

        if (parentVtableAddr != null)
        {
            Data dParent = getDataAt(parentVtableAddr).getComponent(pos);
            if (dParent.getValue().equals(d.getValue()))
            {
                println("skipping "+fnName);
                return;
            }
        }

        DataType dataType = manager.getDataType("/codegen.h/"+className);
        DataType thisType = new PointerDataType(dataType);

        applyFunctionType((Address)d.getValue(), fnName, fnDataType, thisType);
    }

    void applyVmethodTypes(Address vtableAddr, String className, String vtTypeName, Address parentVtableAddr) throws Exception
    {
        println("processing vtable for " + className+ " "+parentVtableAddr);

        Structure vtType = (Structure) manager.getDataType("/codegen.h/"+vtTypeName);
        for (int i = 0; i < vtType.getNumComponents(); i++) {
            DataTypeComponent dc = vtType.getComponent(i);
            String fnName = className + "_" + dc.getFieldName();
            DataType fieldType = dc.getDataType();
            if (fieldType instanceof TypeDef)
            {
                Pointer ptrDataType = (Pointer) ((TypeDef)fieldType).getBaseDataType();
                FunctionDefinition fnDataType = (FunctionDefinition) ptrDataType.getDataType();
                applyVmethodType(vtableAddr, i, className, fnName, fnDataType, parentVtableAddr);
            }
        }
    }

    void createVtable(Address vtableAddr, String className) throws Exception
    {
        DataType dataType = manager.getDataType("/codegen.h/vtable_"+className);
        
        clearListing(vtableAddr, vtableAddr.add(dataType.getLength()));
        createData(vtableAddr, dataType);
        createLabel(vtableAddr, "_vtable_"+className, true, SourceType.USER_DEFINED);
    }

    void createGlobal(Address addr, String name, String typeName) throws Exception
    {
        if (typeName != null && !typeName.equals(""))
        {
            DataType dataType = getDataTypes(typeName)[0];//manager.getDataType("/codegen.h/"+typeName);
        
            clearListing(addr, addr.add(dataType.getLength()));
            createData(addr, dataType);
        }

        createLabel(addr, name, true, SourceType.USER_DEFINED);
    }
    void globals() throws Exception {
createGlobal(toAddr(0x789c1cL), "_cursor", "");
createGlobal(toAddr(0x789c28L), "_selection_rect", "");
createGlobal(toAddr(0x789c40L), "_gamemode", "");
createGlobal(toAddr(0x789c44L), "_gametype", "");
createGlobal(toAddr(0x789c60L), "_ui_menu_width", "int8_t");
createGlobal(toAddr(0x789c61L), "_ui_area_map_width", "int8_t");
createGlobal(toAddr(0xe9d828L), "_created_item_type", "");
createGlobal(toAddr(0xea0560L), "_created_item_subtype", "");
createGlobal(toAddr(0xac6430L), "_created_item_material", "");
createGlobal(toAddr(0xac6440L), "_created_item_matgloss", "");
createGlobal(toAddr(0xea0598L), "_created_item_count", "");
createGlobal(toAddr(0x7a59b8L), "_enabler", "enabler");
createGlobal(toAddr(0xe9d868L), "_flows", "");
createGlobal(toAddr(0xabfad0L), "_gps", "graphic");
createGlobal(toAddr(0xcc5f98L), "_gview", "interfacest");
createGlobal(toAddr(0xaa9288L), "_init", "init");
createGlobal(toAddr(0xb52df0L), "_timed_events", "");
createGlobal(toAddr(0xa82a38L), "_ui", "ui");
createGlobal(toAddr(0xe9e438L), "_ui_advmode", "ui_advmode");
createGlobal(toAddr(0xe9e508L), "_ui_build_selector", "ui_build_selector");
createGlobal(toAddr(0xe9d4d0L), "_ui_building_assign_type", "");
createGlobal(toAddr(0xea0588L), "_ui_building_assign_is_marked", "");
createGlobal(toAddr(0xa90b28L), "_ui_building_assign_units", "");
createGlobal(toAddr(0xe89c20L), "_ui_building_assign_items", "");
createGlobal(toAddr(0xe9d818L), "_ui_look_list", "ui_look_list");
createGlobal(toAddr(0xea05b0L), "_ui_sidebar_menus", "ui_sidebar_menus");
createGlobal(toAddr(0xacb278L), "_world", "world");
createGlobal(toAddr(0xaa91e0L), "_cur_year", "int32_t");
createGlobal(toAddr(0xea0548L), "_cur_year_tick", "int32_t");
createGlobal(toAddr(0xe9d860L), "_cur_year_tick_advmode", "int32_t");
createGlobal(toAddr(0xea05a8L), "_cur_season", "int8_t");
createGlobal(toAddr(0xac6450L), "_cur_season_tick", "int16_t");
createGlobal(toAddr(0xe9d858L), "_current_weather", "");
createGlobal(toAddr(0xf1719eL), "_pause_state", "bool");
createGlobal(toAddr(0xf17196L), "_process_dig", "bool");
createGlobal(toAddr(0xf17197L), "_process_jobs", "bool");
createGlobal(toAddr(0xf1719cL), "_ui_building_in_assign", "bool");
createGlobal(toAddr(0xf1719bL), "_ui_building_in_resize", "bool");
createGlobal(toAddr(0xf17118L), "_ui_building_item_cursor", "");
createGlobal(toAddr(0xaa926cL), "_ui_look_cursor", "");
createGlobal(toAddr(0xea0558L), "_ui_selected_unit", "");
createGlobal(toAddr(0xe9e5f4L), "_ui_unit_view_mode", "ui_unit_view_mode");
createGlobal(toAddr(0xaa920dL), "_ui_workshop_in_add", "bool");
createGlobal(toAddr(0xea05acL), "_ui_workshop_job_cursor", "");
createGlobal(toAddr(0xe89c3cL), "_window_x", "int32_t");
createGlobal(toAddr(0xe89c30L), "_window_y", "int32_t");
createGlobal(toAddr(0xe89c34L), "_window_z", "int32_t");
createGlobal(toAddr(0xf171aaL), "_debug_nopause", "bool");
createGlobal(toAddr(0xf171abL), "_debug_nomoods", "bool");
createGlobal(toAddr(0xf171acL), "_debug_combat", "bool");
createGlobal(toAddr(0xf171adL), "_debug_wildlife", "bool");
createGlobal(toAddr(0xf171aeL), "_debug_nodrink", "bool");
createGlobal(toAddr(0xf171afL), "_debug_noeat", "bool");
createGlobal(toAddr(0xf171b0L), "_debug_nosleep", "bool");
createGlobal(toAddr(0xf171b1L), "_debug_showambush", "bool");
createGlobal(toAddr(0xf171b2L), "_debug_fastmining", "bool");
createGlobal(toAddr(0xf171b3L), "_debug_nothought", "bool");
createGlobal(toAddr(0xf171b4L), "_debug_noberserk", "bool");
createGlobal(toAddr(0xf171b6L), "_debug_turbospeed", "bool");
createGlobal(toAddr(0xF17198L), "_save_on_exit", "bool");
createGlobal(toAddr(0x00789c48L), "_standing_orders_gather_minerals", "uint8_t");
createGlobal(toAddr(0x00789c49L), "_standing_orders_gather_wood", "uint8_t");
createGlobal(toAddr(0x00789c4aL), "_standing_orders_gather_food", "uint8_t");
createGlobal(toAddr(0x00789c4bL), "_standing_orders_gather_bodies", "uint8_t");
createGlobal(toAddr(0x00789c4dL), "_standing_orders_gather_animals", "uint8_t");
createGlobal(toAddr(0x00789c4eL), "_standing_orders_gather_furniture", "uint8_t");
createGlobal(toAddr(0x00789c4fL), "_standing_orders_farmer_harvest", "uint8_t");
createGlobal(toAddr(0x00789c63L), "_standing_orders_job_cancel_announce", "uint8_t");
createGlobal(toAddr(0x00789c64L), "_standing_orders_mix_food", "uint8_t");
createGlobal(toAddr(0x00789c4cL), "_standing_orders_gather_refuse", "uint8_t");
createGlobal(toAddr(0x00f171a1L), "_standing_orders_gather_refuse_outside", "uint8_t");
createGlobal(toAddr(0x00f171a2L), "_standing_orders_dump_corpses", "uint8_t");
createGlobal(toAddr(0x00f171a3L), "_standing_orders_dump_skulls", "uint8_t");
createGlobal(toAddr(0x00f171a4L), "_standing_orders_dump_skins", "uint8_t");
createGlobal(toAddr(0x00f171a5L), "_standing_orders_dump_bones", "uint8_t");
createGlobal(toAddr(0x00f171a6L), "_standing_orders_dump_shells", "uint8_t");
createGlobal(toAddr(0x00f171a7L), "_standing_orders_dump_other", "uint8_t");
createGlobal(toAddr(0x00789c50L), "_standing_orders_auto_loom", "uint8_t");
createGlobal(toAddr(0x00789c51L), "_standing_orders_auto_collect_webs", "uint8_t");
createGlobal(toAddr(0x00789c52L), "_standing_orders_auto_slaughter", "uint8_t");
createGlobal(toAddr(0x00789c53L), "_standing_orders_auto_butcher", "uint8_t");
createGlobal(toAddr(0x00789c54L), "_standing_orders_auto_tan", "uint8_t");
createGlobal(toAddr(0x00f171a0L), "_standing_orders_use_dyed_cloth", "uint8_t");
createGlobal(toAddr(0x00f1719fL), "_standing_orders_stay_indoors", "uint8_t");
createGlobal(toAddr(0xaa91dcL), "_art_image_chunk_next_id", "int32_t");
createGlobal(toAddr(0xaa91d8L), "_artifact_next_id", "int32_t");
createGlobal(toAddr(0xac6454L), "_building_next_id", "int32_t");
createGlobal(toAddr(0xaa91e8L), "_entity_next_id", "int32_t");
createGlobal(toAddr(0xea0554L), "_hist_event_next_id", "int32_t");
createGlobal(toAddr(0xe9e5f0L), "_hist_figure_next_id", "int32_t");
createGlobal(toAddr(0xea10f8L), "_item_next_id", "int32_t");
createGlobal(toAddr(0xaa9268L), "_job_next_id", "int32_t");
createGlobal(toAddr(0xea053cL), "_nemesis_next_id", "int32_t");
createGlobal(toAddr(0xf17128L), "_proj_next_id", "int32_t");
createGlobal(toAddr(0xe9e430L), "_schedule_next_id", "int32_t");
createGlobal(toAddr(0xe9d814L), "_task_next_id", "int32_t");
createGlobal(toAddr(0xe9d85cL), "_unit_chunk_next_id", "int32_t");
createGlobal(toAddr(0xe89c38L), "_unit_next_id", "int32_t");
createGlobal(toAddr(0x57e420L), "_func_render", "");
createGlobal(toAddr(0x5d9190L), "_func_item_categorize", "");
createGlobal(toAddr(0x5da8f0L), "_func_item_uncategorize", "");
}
    void vtables() throws Exception {
createGlobal(toAddr(0x75CDE8L), "_vtable_active_script_var_longst", "vtable_active_script_varst");
createGlobal(toAddr(0x75CDCCL), "_vtable_active_script_var_unitst", "vtable_active_script_varst");
createGlobal(toAddr(0x7530A0L), "_vtable_art_image_element_creaturest", "vtable_art_image_elementst");
createGlobal(toAddr(0x753000L), "_vtable_art_image_element_itemst", "vtable_art_image_elementst");
createGlobal(toAddr(0x753078L), "_vtable_art_image_element_plantst", "vtable_art_image_elementst");
createGlobal(toAddr(0x753028L), "_vtable_art_image_element_shapest", "vtable_art_image_elementst");
createGlobal(toAddr(0x753050L), "_vtable_art_image_element_treest", "vtable_art_image_elementst");
createGlobal(toAddr(0x753118L), "_vtable_art_image_elementst", "vtable_art_image_elementst");
createGlobal(toAddr(0x7530E0L), "_vtable_art_image_property_intransitive_verbst", "vtable_art_image_propertyst");
createGlobal(toAddr(0x7530C8L), "_vtable_art_image_property_transitive_verbst", "vtable_art_image_propertyst");
createGlobal(toAddr(0x7530F8L), "_vtable_art_image_propertyst", "vtable_art_image_propertyst");
createGlobal(toAddr(0x753810L), "_vtable_building_actualst", "vtable_building_actualst");
createGlobal(toAddr(0x755DA4L), "_vtable_building_animaltrapst", "vtable_building_actualst");
createGlobal(toAddr(0x7548D4L), "_vtable_building_aqueductst", "vtable_building_actualst");
createGlobal(toAddr(0x754D74L), "_vtable_building_archerytargetst", "vtable_building_actualst");
createGlobal(toAddr(0x753A60L), "_vtable_building_armorstandst", "vtable_building_actualst");
createGlobal(toAddr(0x755214L), "_vtable_building_bedst", "vtable_building_actualst");
createGlobal(toAddr(0x75430CL), "_vtable_building_boxst", "vtable_building_actualst");
createGlobal(toAddr(0x754684L), "_vtable_building_bridgest", "vtable_building_actualst");
createGlobal(toAddr(0x754434L), "_vtable_building_cabinetst", "vtable_building_actualst");
createGlobal(toAddr(0x754FC4L), "_vtable_building_cagest", "vtable_building_actualst");
createGlobal(toAddr(0x754E9CL), "_vtable_building_chainst", "vtable_building_actualst");
createGlobal(toAddr(0x755464L), "_vtable_building_chairst", "vtable_building_actualst");
createGlobal(toAddr(0x755B54L), "_vtable_building_channelst", "vtable_building_actualst");
createGlobal(toAddr(0x7541F0L), "_vtable_building_civzonest", "vtable_buildingst");
createGlobal(toAddr(0x7556B4L), "_vtable_building_coffinst", "vtable_building_actualst");
createGlobal(toAddr(0x75455CL), "_vtable_building_doorst", "vtable_building_actualst");
createGlobal(toAddr(0x755C7CL), "_vtable_building_farmplotst", "vtable_building_actualst");
createGlobal(toAddr(0x7547ACL), "_vtable_building_floodgatest", "vtable_building_actualst");
createGlobal(toAddr(0x755ECCL), "_vtable_building_furnacest", "vtable_building_actualst");
createGlobal(toAddr(0x75636CL), "_vtable_building_roadst", "vtable_building_actualst");
createGlobal(toAddr(0x75558CL), "_vtable_building_shopst", "vtable_building_actualst");
createGlobal(toAddr(0x7550ECL), "_vtable_building_siegeenginest", "vtable_building_actualst");
createGlobal(toAddr(0x755904L), "_vtable_building_statuest", "vtable_building_actualst");
createGlobal(toAddr(0x7540D4L), "_vtable_building_stockpilest", "vtable_buildingst");
createGlobal(toAddr(0x754B24L), "_vtable_building_supportst", "vtable_building_actualst");
createGlobal(toAddr(0x75533CL), "_vtable_building_tablest", "vtable_building_actualst");
createGlobal(toAddr(0x75611CL), "_vtable_building_tradedepotst", "vtable_building_actualst");
createGlobal(toAddr(0x7549FCL), "_vtable_building_trapst", "vtable_building_actualst");
createGlobal(toAddr(0x756244L), "_vtable_building_wagonst", "vtable_building_actualst");
createGlobal(toAddr(0x753938L), "_vtable_building_weaponrackst", "vtable_building_actualst");
createGlobal(toAddr(0x754C4CL), "_vtable_building_weaponst", "vtable_building_actualst");
createGlobal(toAddr(0x7557DCL), "_vtable_building_wellst", "vtable_building_actualst");
createGlobal(toAddr(0x755A2CL), "_vtable_building_windowst", "vtable_building_actualst");
createGlobal(toAddr(0x755FF4L), "_vtable_building_workshopst", "vtable_building_actualst");
createGlobal(toAddr(0x753194L), "_vtable_buildingst", "vtable_buildingst");
createGlobal(toAddr(0x7658B4L), "_vtable_general_ref_artifactst", "vtable_general_refst");
createGlobal(toAddr(0x765FECL), "_vtable_general_ref_building_cagedst", "vtable_general_refst");
createGlobal(toAddr(0x766018L), "_vtable_general_ref_building_chainst", "vtable_general_refst");
createGlobal(toAddr(0x76609CL), "_vtable_general_ref_building_civzone_assignedst", "vtable_general_refst");
createGlobal(toAddr(0x765F94L), "_vtable_general_ref_building_holderst", "vtable_general_refst");
createGlobal(toAddr(0x766070L), "_vtable_general_ref_building_triggerst", "vtable_general_refst");
createGlobal(toAddr(0x766044L), "_vtable_general_ref_building_triggertargetst", "vtable_general_refst");
createGlobal(toAddr(0x765FC0L), "_vtable_general_ref_building_channeledst", "vtable_general_refst");
createGlobal(toAddr(0x7660C8L), "_vtable_general_ref_buildingst", "vtable_general_refst");
createGlobal(toAddr(0x75D4BCL), "_vtable_general_ref_coinbatchst", "vtable_general_refst");
createGlobal(toAddr(0x76614CL), "_vtable_general_ref_contained_in_itemst", "vtable_general_refst");
createGlobal(toAddr(0x766228L), "_vtable_general_ref_contains_itemst", "vtable_general_refst");
createGlobal(toAddr(0x766280L), "_vtable_general_ref_contains_unitst", "vtable_general_refst");
createGlobal(toAddr(0x75A5B0L), "_vtable_general_ref_entity_art_imagest", "vtable_general_refst");
createGlobal(toAddr(0x765888L), "_vtable_general_ref_item_typest", "vtable_general_refst");
createGlobal(toAddr(0x766254L), "_vtable_general_ref_itemst", "vtable_general_refst");
createGlobal(toAddr(0x7658E0L), "_vtable_general_ref_mapsquarest", "vtable_general_refst");
createGlobal(toAddr(0x7661FCL), "_vtable_general_ref_projectilest", "vtable_general_refst");
createGlobal(toAddr(0x766120L), "_vtable_general_ref_unit_holderst", "vtable_general_refst");
createGlobal(toAddr(0x7661A4L), "_vtable_general_ref_unit_itemownerst", "vtable_general_refst");
createGlobal(toAddr(0x766178L), "_vtable_general_ref_unit_tradebringerst", "vtable_general_refst");
createGlobal(toAddr(0x7661D0L), "_vtable_general_ref_unit_traineest", "vtable_general_refst");
createGlobal(toAddr(0x7660F4L), "_vtable_general_ref_unit_workerst", "vtable_general_refst");
createGlobal(toAddr(0x7662ACL), "_vtable_general_ref_unitst", "vtable_general_refst");
createGlobal(toAddr(0x75A5DCL), "_vtable_general_refst", "vtable_general_refst");
createGlobal(toAddr(0x75C8ECL), "_vtable_history_event_add_hf_entity_linkst", "vtable_history_eventst");
createGlobal(toAddr(0x75C640L), "_vtable_history_event_agreements_voidedst", "vtable_history_eventst");
createGlobal(toAddr(0x75C008L), "_vtable_history_event_artifact_createdst", "vtable_history_eventst");
createGlobal(toAddr(0x75CABCL), "_vtable_history_event_artifact_droppedst", "vtable_history_eventst");
createGlobal(toAddr(0x75C9D4L), "_vtable_history_event_artifact_foundst", "vtable_history_eventst");
createGlobal(toAddr(0x75874CL), "_vtable_history_event_artifact_hiddenst", "vtable_history_eventst");
createGlobal(toAddr(0x75C22CL), "_vtable_history_event_artifact_lostst", "vtable_history_eventst");
createGlobal(toAddr(0x7587C0L), "_vtable_history_event_artifact_possessedst", "vtable_history_eventst");
createGlobal(toAddr(0x75CA48L), "_vtable_history_event_artifact_recoveredst", "vtable_history_eventst");
createGlobal(toAddr(0x75C804L), "_vtable_history_event_created_sitest", "vtable_history_eventst");
createGlobal(toAddr(0x75CB30L), "_vtable_history_event_demon_encasedst", "vtable_history_eventst");
createGlobal(toAddr(0x75CBA4L), "_vtable_history_event_demon_releasedst", "vtable_history_eventst");
createGlobal(toAddr(0x75C5CCL), "_vtable_history_event_diplomat_lostst", "vtable_history_eventst");
createGlobal(toAddr(0x75C558L), "_vtable_history_event_first_contact_failedst", "vtable_history_eventst");
createGlobal(toAddr(0x75C2A0L), "_vtable_history_event_first_contactst", "vtable_history_eventst");
createGlobal(toAddr(0x75884CL), "_vtable_history_event_hf_contact_lostst", "");
createGlobal(toAddr(0x7589D0L), "_vtable_history_event_hf_destroyed_sitest", "vtable_history_eventst");
createGlobal(toAddr(0x7588C0L), "_vtable_history_event_hist_figure_diedst", "vtable_history_eventst");
createGlobal(toAddr(0x75C960L), "_vtable_history_event_merchantst", "vtable_history_eventst");
createGlobal(toAddr(0x75C878L), "_vtable_history_event_reclaim_sitest", "vtable_history_eventst");
createGlobal(toAddr(0x758AB8L), "_vtable_history_event_site_abandonedst", "vtable_history_eventst");
createGlobal(toAddr(0x758A44L), "_vtable_history_event_site_diedst", "vtable_history_eventst");
createGlobal(toAddr(0x75C314L), "_vtable_history_event_topicagreement_concludedst", "vtable_history_eventst");
createGlobal(toAddr(0x75C3FCL), "_vtable_history_event_topicagreement_madest", "vtable_history_eventst");
createGlobal(toAddr(0x75C388L), "_vtable_history_event_topicagreement_rejectedst", "vtable_history_eventst");
createGlobal(toAddr(0x75C790L), "_vtable_history_event_war_attacked_sitest", "vtable_history_eventst");
createGlobal(toAddr(0x75895CL), "_vtable_history_event_war_destroyed_sitest", "vtable_history_eventst");
createGlobal(toAddr(0x75C470L), "_vtable_history_event_war_peace_acceptedst", "vtable_history_eventst");
createGlobal(toAddr(0x75C4E4L), "_vtable_history_event_war_peace_rejectedst", "vtable_history_eventst");
createGlobal(toAddr(0x75C71CL), "_vtable_history_eventst", "vtable_history_eventst");
createGlobal(toAddr(0x758934L), "_vtable_interface_button_building_category_selectorst", "vtable_interface_buttonst");
createGlobal(toAddr(0x758948L), "_vtable_interface_button_building_material_selectorst", "vtable_interface_buttonst");
createGlobal(toAddr(0x758B40L), "_vtable_interface_button_building_new_jobst", "vtable_interface_buttonst");
createGlobal(toAddr(0x758BA4L), "_vtable_interface_button_building_permit_foreign_armorst", "vtable_interface_buttonst");
createGlobal(toAddr(0x758B7CL), "_vtable_interface_button_building_permit_foreign_siegeammost", "vtable_interface_buttonst");
createGlobal(toAddr(0x758B68L), "_vtable_interface_button_building_permit_foreign_weaponst", "vtable_interface_buttonst");
createGlobal(toAddr(0x758B90L), "_vtable_interface_button_building_permit_itemst", "vtable_interface_buttonst");
createGlobal(toAddr(0x758B54L), "_vtable_interface_button_building_permit_trapcompst", "vtable_interface_buttonst");
createGlobal(toAddr(0x75CCC0L), "_vtable_interface_button_buildingst", "vtable_interface_buttonst");
createGlobal(toAddr(0x75CE54L), "_vtable_interface_button_button_designate_selectst", "vtable_interface_buttonst");
createGlobal(toAddr(0x75CE68L), "_vtable_interface_button_button_donest", "vtable_interface_buttonst");
createGlobal(toAddr(0x75CE04L), "_vtable_interface_button_button_light_up_selectorst", "vtable_interface_buttonst");
createGlobal(toAddr(0x75CCE8L), "_vtable_interface_button_buttonst", "vtable_interface_buttonst");
createGlobal(toAddr(0x75CE2CL), "_vtable_interface_button_construction_building_selectorst", "vtable_interface_buttonst");
createGlobal(toAddr(0x75CE18L), "_vtable_interface_button_construction_category_selectorst", "vtable_interface_buttonst");
createGlobal(toAddr(0x75CE40L), "_vtable_interface_button_construction_donest", "vtable_interface_buttonst");
createGlobal(toAddr(0x75CCD4L), "_vtable_interface_button_constructionst", "vtable_interface_buttonst");
createGlobal(toAddr(0x758B2CL), "_vtable_interface_buttonst", "vtable_interface_buttonst");
createGlobal(toAddr(0x753580L), "_vtable_item_actualst", "vtable_item_actualst");
createGlobal(toAddr(0x758EA0L), "_vtable_item_ammost", "vtable_item_actualst");
createGlobal(toAddr(0x763400L), "_vtable_item_amuletst", "vtable_item_actualst");
createGlobal(toAddr(0x761F80L), "_vtable_item_animaltrapst", "vtable_item_actualst");
createGlobal(toAddr(0x7645F0L), "_vtable_item_anvilst", "vtable_item_actualst");
createGlobal(toAddr(0x759130L), "_vtable_item_armorst", "vtable_item_actualst");
createGlobal(toAddr(0x7629C0L), "_vtable_item_armorstandst", "vtable_item_actualst");
createGlobal(toAddr(0x7584A4L), "_vtable_item_backpackst", "vtable_item_actualst");
createGlobal(toAddr(0x760350L), "_vtable_item_ballistaarrowheadst", "vtable_item_actualst");
createGlobal(toAddr(0x764DA0L), "_vtable_item_ballistapartsst", "vtable_item_actualst");
createGlobal(toAddr(0x75A090L), "_vtable_item_barrelst", "vtable_item_actualst");
createGlobal(toAddr(0x75D530L), "_vtable_item_barst", "vtable_item_actualst");
createGlobal(toAddr(0x75A898L), "_vtable_item_bedst", "vtable_item_actualst");
createGlobal(toAddr(0x762730L), "_vtable_item_binst", "vtable_item_actualst");
createGlobal(toAddr(0x75DA50L), "_vtable_item_blocksst", "vtable_item_actualst");
createGlobal(toAddr(0x75BAE8L), "_vtable_item_bonesst", "vtable_item_actualst");
createGlobal(toAddr(0x758214L), "_vtable_item_boxst", "vtable_item_actualst");
createGlobal(toAddr(0x7640D0L), "_vtable_item_braceletst", "vtable_item_actualst");
createGlobal(toAddr(0x761CF0L), "_vtable_item_bucketst", "vtable_item_actualst");
createGlobal(toAddr(0x762EE0L), "_vtable_item_cabinetst", "vtable_item_actualst");
createGlobal(toAddr(0x761A60L), "_vtable_item_cagest", "vtable_item_actualst");
createGlobal(toAddr(0x764B10L), "_vtable_item_catapultpartsst", "vtable_item_actualst");
createGlobal(toAddr(0x760D90L), "_vtable_item_chainst", "vtable_item_actualst");
createGlobal(toAddr(0x75AB28L), "_vtable_item_chairst", "vtable_item_actualst");
createGlobal(toAddr(0x7605E0L), "_vtable_item_cheesest", "vtable_item_actualst");
createGlobal(toAddr(0x760870L), "_vtable_item_clothst", "vtable_item_actualst");
createGlobal(toAddr(0x762210L), "_vtable_item_coffinst", "vtable_item_actualst");
createGlobal(toAddr(0x757024L), "_vtable_item_coinst", "vtable_item_actualst");
createGlobal(toAddr(0x75A608L), "_vtable_item_constructedst", "vtable_item_actualst");
createGlobal(toAddr(0x75F3F0L), "_vtable_item_corpsepiecest", "vtable_item_actualst");
createGlobal(toAddr(0x75B338L), "_vtable_item_corpsest", "vtable_item_actualst");
createGlobal(toAddr(0x757A64L), "_vtable_item_craftedst", "vtable_item_actualst");
createGlobal(toAddr(0x765B9CL), "_vtable_item_critterst", "vtable_item_actualst");
createGlobal(toAddr(0x763920L), "_vtable_item_crownst", "vtable_item_actualst");
createGlobal(toAddr(0x7577D4L), "_vtable_item_doorst", "vtable_item_actualst");
createGlobal(toAddr(0x75EED0L), "_vtable_item_drinkst", "vtable_item_actualst");
createGlobal(toAddr(0x763E40L), "_vtable_item_earringst", "vtable_item_actualst");
createGlobal(toAddr(0x75E9B0L), "_vtable_item_extractst", "vtable_item_actualst");
createGlobal(toAddr(0x763170L), "_vtable_item_figurinest", "vtable_item_actualst");
createGlobal(toAddr(0x75F680L), "_vtable_item_fish_rawst", "vtable_item_actualst");
createGlobal(toAddr(0x757F84L), "_vtable_item_fishst", "vtable_item_actualst");
createGlobal(toAddr(0x7572B4L), "_vtable_item_flaskst", "vtable_item_actualst");
createGlobal(toAddr(0x760B00L), "_vtable_item_floodgatest", "vtable_item_actualst");
createGlobal(toAddr(0x75D228L), "_vtable_item_foodst", "vtable_item_actualst");
createGlobal(toAddr(0x764360L), "_vtable_item_gemst", "vtable_item_actualst");
createGlobal(toAddr(0x75685CL), "_vtable_item_globst", "vtable_item_actualst");
createGlobal(toAddr(0x759B70L), "_vtable_item_glovesst", "vtable_item_actualst");
createGlobal(toAddr(0x761020L), "_vtable_item_gobletst", "vtable_item_actualst");
createGlobal(toAddr(0x759E00L), "_vtable_item_helmst", "vtable_item_actualst");
createGlobal(toAddr(0x7612B0L), "_vtable_item_instrumentst", "vtable_item_actualst");
createGlobal(toAddr(0x7600C0L), "_vtable_item_leavesst", "vtable_item_actualst");
createGlobal(toAddr(0x7565CCL), "_vtable_item_liquid_miscst", "vtable_item_actualst");
createGlobal(toAddr(0x756AECL), "_vtable_item_liquidst", "vtable_item_actualst");
createGlobal(toAddr(0x76590CL), "_vtable_item_liquipowderst", "vtable_item_actualst");
createGlobal(toAddr(0x757CF4L), "_vtable_item_meatst", "vtable_item_actualst");
createGlobal(toAddr(0x75DCE0L), "_vtable_item_orest", "vtable_item_actualst");
createGlobal(toAddr(0x7598E0L), "_vtable_item_pantsst", "vtable_item_actualst");
createGlobal(toAddr(0x75F910L), "_vtable_item_petst", "vtable_item_actualst");
createGlobal(toAddr(0x753E18L), "_vtable_item_plantst", "vtable_item_actualst");
createGlobal(toAddr(0x75EC40L), "_vtable_item_potionst", "vtable_item_actualst");
createGlobal(toAddr(0x75F160L), "_vtable_item_powder_organicst", "vtable_item_actualst");
createGlobal(toAddr(0x75B048L), "_vtable_item_powderst", "vtable_item_actualst");
createGlobal(toAddr(0x75A320L), "_vtable_item_quiverst", "vtable_item_actualst");
createGlobal(toAddr(0x753B88L), "_vtable_item_remainsst", "vtable_item_actualst");
createGlobal(toAddr(0x763BB0L), "_vtable_item_ringst", "vtable_item_actualst");
createGlobal(toAddr(0x75E490L), "_vtable_item_rockst", "vtable_item_actualst");
createGlobal(toAddr(0x75DF70L), "_vtable_item_roughst", "vtable_item_actualst");
createGlobal(toAddr(0x75ADB8L), "_vtable_item_sandst", "vtable_item_actualst");
createGlobal(toAddr(0x763690L), "_vtable_item_scepterst", "vtable_item_actualst");
createGlobal(toAddr(0x75B5C8L), "_vtable_item_seedsst", "vtable_item_actualst");
createGlobal(toAddr(0x75FE30L), "_vtable_item_shellst", "vtable_item_actualst");
createGlobal(toAddr(0x759650L), "_vtable_item_shieldst", "vtable_item_actualst");
createGlobal(toAddr(0x7593C0L), "_vtable_item_shoesst", "vtable_item_actualst");
createGlobal(toAddr(0x765030L), "_vtable_item_siegeammost", "vtable_item_actualst");
createGlobal(toAddr(0x75B858L), "_vtable_item_skin_rawst", "vtable_item_actualst");
createGlobal(toAddr(0x75FBA0L), "_vtable_item_skin_tannedst", "vtable_item_actualst");
createGlobal(toAddr(0x75BD78L), "_vtable_item_skullst", "vtable_item_actualst");
createGlobal(toAddr(0x75D7C0L), "_vtable_item_smallgemst", "vtable_item_actualst");
createGlobal(toAddr(0x7624A0L), "_vtable_item_statuest", "vtable_item_actualst");
createGlobal(toAddr(0x75E200L), "_vtable_item_stonest", "vtable_item_actualst");
createGlobal(toAddr(0x757544L), "_vtable_item_tablest", "vtable_item_actualst");
createGlobal(toAddr(0x756D7CL), "_vtable_item_threadst", "vtable_item_actualst");
createGlobal(toAddr(0x764880L), "_vtable_item_totemst", "vtable_item_actualst");
createGlobal(toAddr(0x761540L), "_vtable_item_toyst", "vtable_item_actualst");
createGlobal(toAddr(0x765550L), "_vtable_item_trapcompst", "vtable_item_actualst");
createGlobal(toAddr(0x7652C0L), "_vtable_item_trappartsst", "vtable_item_actualst");
createGlobal(toAddr(0x7532B0L), "_vtable_item_verminst", "vtable_item_actualst");
createGlobal(toAddr(0x762C50L), "_vtable_item_weaponrackst", "vtable_item_actualst");
createGlobal(toAddr(0x758C10L), "_vtable_item_weaponst", "vtable_item_actualst");
createGlobal(toAddr(0x7617D0L), "_vtable_item_windowst", "vtable_item_actualst");
createGlobal(toAddr(0x75E720L), "_vtable_item_woodst", "vtable_item_actualst");
createGlobal(toAddr(0x765828L), "_vtable_itemdef_ammost", "vtable_itemdefst");
createGlobal(toAddr(0x76581CL), "_vtable_itemdef_armorst", "vtable_itemdefst");
createGlobal(toAddr(0x76587CL), "_vtable_itemdef_foodst", "vtable_itemdefst");
createGlobal(toAddr(0x765840L), "_vtable_itemdef_glovesst", "vtable_itemdefst");
createGlobal(toAddr(0x765864L), "_vtable_itemdef_helmst", "vtable_itemdefst");
createGlobal(toAddr(0x765810L), "_vtable_itemdef_instrumentst", "vtable_itemdefst");
createGlobal(toAddr(0x765870L), "_vtable_itemdef_pantsst", "vtable_itemdefst");
createGlobal(toAddr(0x765858L), "_vtable_itemdef_shieldst", "vtable_itemdefst");
createGlobal(toAddr(0x76584CL), "_vtable_itemdef_shoesst", "vtable_itemdefst");
createGlobal(toAddr(0x765834L), "_vtable_itemdef_siegeammost", "vtable_itemdefst");
createGlobal(toAddr(0x765804L), "_vtable_itemdef_toyst", "vtable_itemdefst");
createGlobal(toAddr(0x7657F8L), "_vtable_itemdef_trapcompst", "vtable_itemdefst");
createGlobal(toAddr(0x7657ECL), "_vtable_itemdef_weaponst", "vtable_itemdefst");
createGlobal(toAddr(0x7657E0L), "_vtable_itemdefst", "vtable_itemdefst");
createGlobal(toAddr(0x75D204L), "_vtable_itemimprovement_art_imagest", "vtable_itemimprovementst");
createGlobal(toAddr(0x75D198L), "_vtable_itemimprovement_bandsst", "vtable_itemimprovementst");
createGlobal(toAddr(0x75D108L), "_vtable_itemimprovement_clothst", "vtable_itemimprovementst");
createGlobal(toAddr(0x75D1E0L), "_vtable_itemimprovement_coveredst", "vtable_itemimprovementst");
createGlobal(toAddr(0x75D150L), "_vtable_itemimprovement_itemspecificst", "vtable_itemimprovementst");
createGlobal(toAddr(0x75D1BCL), "_vtable_itemimprovement_rings_hangingst", "vtable_itemimprovementst");
createGlobal(toAddr(0x75D50CL), "_vtable_itemimprovement_sewn_imagest", "vtable_itemimprovementst");
createGlobal(toAddr(0x75D174L), "_vtable_itemimprovement_spikesst", "vtable_itemimprovementst");
createGlobal(toAddr(0x75D12CL), "_vtable_itemimprovement_threadst", "vtable_itemimprovementst");
createGlobal(toAddr(0x75D4E8L), "_vtable_itemimprovementst", "vtable_itemimprovementst");
createGlobal(toAddr(0x75CE7CL), "_vtable_itemst", "vtable_itemst");
createGlobal(toAddr(0x75CCFCL), "_vtable_layer_object_buttonst", "vtable_layer_objectst");
createGlobal(toAddr(0x75CD40L), "_vtable_layer_object_listst", "vtable_layer_objectst");
createGlobal(toAddr(0x753540L), "_vtable_proj_itemst", "vtable_projst");
createGlobal(toAddr(0x765F78L), "_vtable_proj_magicst", "vtable_projst");
createGlobal(toAddr(0x756494L), "_vtable_proj_unitst", "vtable_projst");
createGlobal(toAddr(0x7540B8L), "_vtable_projst", "vtable_projst");
createGlobal(toAddr(0x766350L), "_vtable_script_step_conditionalst", "vtable_script_stepst");
createGlobal(toAddr(0x7662F8L), "_vtable_script_step_constructtopiclistst", "vtable_script_stepst");
createGlobal(toAddr(0x766390L), "_vtable_script_step_dipeventst", "vtable_script_stepst");
createGlobal(toAddr(0x766328L), "_vtable_script_step_diphistoryst", "vtable_script_stepst");
createGlobal(toAddr(0x766318L), "_vtable_script_step_discussst", "vtable_script_stepst");
createGlobal(toAddr(0x7662D8L), "_vtable_script_step_invasionst", "vtable_script_stepst");
createGlobal(toAddr(0x766370L), "_vtable_script_step_setvarst", "vtable_script_stepst");
createGlobal(toAddr(0x766360L), "_vtable_script_step_simpleactionst", "vtable_script_stepst");
createGlobal(toAddr(0x766380L), "_vtable_script_step_textviewerst", "vtable_script_stepst");
createGlobal(toAddr(0x766308L), "_vtable_script_step_topicdiscussionst", "vtable_script_stepst");
createGlobal(toAddr(0x7662E8L), "_vtable_script_step_eventst", "vtable_script_stepst");
createGlobal(toAddr(0x766338L), "_vtable_script_stepst", "vtable_script_stepst");
createGlobal(toAddr(0x76634CL), "_vtable_script_var_longst", "vtable_script_varst");
createGlobal(toAddr(0x766348L), "_vtable_script_var_unitst", "vtable_script_varst");
createGlobal(toAddr(0x7564C8L), "_vtable_task_kill_nemesisst", "vtable_taskst");
createGlobal(toAddr(0x7564E8L), "_vtable_taskst", "vtable_taskst");
createGlobal(toAddr(0x758BFCL), "_vtable_text_info_element_longst", "vtable_text_info_elementst");
createGlobal(toAddr(0x758BE4L), "_vtable_text_info_element_stringst", "vtable_text_info_elementst");
createGlobal(toAddr(0x758BF0L), "_vtable_text_info_elementst", "vtable_text_info_elementst");
createGlobal(toAddr(0x7663B8L), "_vtable_vegst", "vtable_vegst");
createGlobal(toAddr(0x75659CL), "_vtable_viewscreen_adventure_logst", "vtable_viewscreenst");
createGlobal(toAddr(0x756524L), "_vtable_viewscreen_adventure_travelst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C07CL), "_vtable_viewscreen_announcelistst", "vtable_viewscreenst");
createGlobal(toAddr(0x765E2CL), "_vtable_viewscreen_assigntradest", "vtable_viewscreenst");
createGlobal(toAddr(0x765E5CL), "_vtable_viewscreen_barterst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C1E4L), "_vtable_viewscreen_buildinglistst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C6E4L), "_vtable_viewscreen_buildingst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C184L), "_vtable_viewscreen_civlistst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C1B4L), "_vtable_viewscreen_commandchainst", "vtable_viewscreenst");
createGlobal(toAddr(0x7564B0L), "_vtable_viewscreen_conversationst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C124L), "_vtable_viewscreen_createquotast", "vtable_viewscreenst");
createGlobal(toAddr(0x75CC78L), "_vtable_viewscreen_customize_unitst", "vtable_viewscreenst");
createGlobal(toAddr(0x756584L), "_vtable_viewscreen_dungeon_announcest", "vtable_viewscreenst");
createGlobal(toAddr(0x75656CL), "_vtable_viewscreen_dungeon_monsterstatusst", "vtable_viewscreenst");
createGlobal(toAddr(0x7565B4L), "_vtable_viewscreen_dungeon_wrestlest", "vtable_viewscreenst");
createGlobal(toAddr(0x756554L), "_vtable_viewscreen_dungeonmodest", "vtable_viewscreenst");
createGlobal(toAddr(0x758734L), "_vtable_viewscreen_dwarfmodest", "vtable_viewscreenst");
createGlobal(toAddr(0x75C16CL), "_vtable_viewscreen_entityst", "vtable_viewscreenst");
createGlobal(toAddr(0x75B2D8L), "_vtable_viewscreen_export_regionst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C6CCL), "_vtable_viewscreen_itemst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C10CL), "_vtable_viewscreen_jobmanagementst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C6FCL), "_vtable_viewscreen_jobst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C0DCL), "_vtable_viewscreen_justicest", "vtable_viewscreenst");
createGlobal(toAddr(0x75CC48L), "_vtable_viewscreen_keybindingsst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C094L), "_vtable_viewscreen_kitchenprefst", "vtable_viewscreenst");
createGlobal(toAddr(0x75CD84L), "_vtable_viewscreen_layer_stockpilest", "vtable_viewscreenst");
createGlobal(toAddr(0x75CDB4L), "_vtable_viewscreen_layer_workshop_profilest", "vtable_viewscreenst");
createGlobal(toAddr(0x75CD9CL), "_vtable_viewscreen_layerst", "vtable_viewscreenst");
createGlobal(toAddr(0x75B308L), "_vtable_viewscreen_legendsst", "vtable_viewscreenst");
createGlobal(toAddr(0x75CCA8L), "_vtable_viewscreen_loadgamest", "vtable_viewscreenst");
createGlobal(toAddr(0x765E8CL), "_vtable_viewscreen_meetingst", "vtable_viewscreenst");
createGlobal(toAddr(0x75CC90L), "_vtable_viewscreen_movieplayerst", "vtable_viewscreenst");
createGlobal(toAddr(0x75B2F0L), "_vtable_viewscreen_new_regionst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C1FCL), "_vtable_viewscreen_noblelistst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C214L), "_vtable_viewscreen_noblest", "vtable_viewscreenst");
createGlobal(toAddr(0x75CC18L), "_vtable_viewscreen_optionst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C1CCL), "_vtable_viewscreen_overallstatusst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C0ACL), "_vtable_viewscreen_petst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C0C4L), "_vtable_viewscreen_pricest", "vtable_viewscreenst");
createGlobal(toAddr(0x765F04L), "_vtable_viewscreen_requestagreementst", "vtable_viewscreenst");
createGlobal(toAddr(0x75CC30L), "_vtable_viewscreen_savegamest", "vtable_viewscreenst");
createGlobal(toAddr(0x758834L), "_vtable_viewscreen_selectitemst", "vtable_viewscreenst");
createGlobal(toAddr(0x75700CL), "_vtable_viewscreen_setupadventurest", "vtable_viewscreenst");
createGlobal(toAddr(0x7663A0L), "_vtable_viewscreen_setupdwarfgamest", "vtable_viewscreenst");
createGlobal(toAddr(0x75C19CL), "_vtable_viewscreen_squadst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C6B4L), "_vtable_viewscreen_storesst", "vtable_viewscreenst");
createGlobal(toAddr(0x765F1CL), "_vtable_viewscreen_textviewerst", "vtable_viewscreenst");
createGlobal(toAddr(0x75B320L), "_vtable_viewscreen_titlest", "vtable_viewscreenst");
createGlobal(toAddr(0x765EBCL), "_vtable_viewscreen_topicmeeting_takerequests_dwarfst", "vtable_viewscreenst");
createGlobal(toAddr(0x765ED4L), "_vtable_viewscreen_topicmeeting_takerequests_humanst", "vtable_viewscreenst");
createGlobal(toAddr(0x765EA4L), "_vtable_viewscreen_topicmeetingst", "vtable_viewscreenst");
createGlobal(toAddr(0x765EECL), "_vtable_viewscreen_tradeagreementst", "vtable_viewscreenst");
createGlobal(toAddr(0x765E74L), "_vtable_viewscreen_tradegoodsst", "vtable_viewscreenst");
createGlobal(toAddr(0x765E44L), "_vtable_viewscreen_tradelistst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C154L), "_vtable_viewscreen_treasurelistst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C13CL), "_vtable_viewscreen_unitjobsst", "vtable_viewscreenst");
createGlobal(toAddr(0x75CC60L), "_vtable_viewscreen_unitst", "vtable_viewscreenst");
createGlobal(toAddr(0x75C0F4L), "_vtable_viewscreen_wagesst", "vtable_viewscreenst");
createGlobal(toAddr(0x75653CL), "_vtable_viewscreenst", "vtable_viewscreenst");
}
    void vmethods() throws Exception {
applyVmethodTypes(toAddr(0x75CDE8L), "active_script_var_longst", "vtable_active_script_varst", null);
applyVmethodTypes(toAddr(0x75CDCCL), "active_script_var_unitst", "vtable_active_script_varst", null);
applyVmethodTypes(toAddr(0x7530A0L), "art_image_element_creaturest", "vtable_art_image_elementst", toAddr(0x753118L));
applyVmethodTypes(toAddr(0x753000L), "art_image_element_itemst", "vtable_art_image_elementst", toAddr(0x753118L));
applyVmethodTypes(toAddr(0x753078L), "art_image_element_plantst", "vtable_art_image_elementst", toAddr(0x753118L));
applyVmethodTypes(toAddr(0x753028L), "art_image_element_shapest", "vtable_art_image_elementst", toAddr(0x753118L));
applyVmethodTypes(toAddr(0x753050L), "art_image_element_treest", "vtable_art_image_elementst", toAddr(0x753118L));
applyVmethodTypes(toAddr(0x753118L), "art_image_elementst", "vtable_art_image_elementst", null);
applyVmethodTypes(toAddr(0x7530E0L), "art_image_property_intransitive_verbst", "vtable_art_image_propertyst", toAddr(0x7530F8L));
applyVmethodTypes(toAddr(0x7530C8L), "art_image_property_transitive_verbst", "vtable_art_image_propertyst", toAddr(0x7530F8L));
applyVmethodTypes(toAddr(0x7530F8L), "art_image_propertyst", "vtable_art_image_propertyst", null);
applyVmethodTypes(toAddr(0x753810L), "building_actualst", "vtable_building_actualst", toAddr(0x753194L));
applyVmethodTypes(toAddr(0x755DA4L), "building_animaltrapst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x7548D4L), "building_aqueductst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x754D74L), "building_archerytargetst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x753A60L), "building_armorstandst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x755214L), "building_bedst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x75430CL), "building_boxst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x754684L), "building_bridgest", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x754434L), "building_cabinetst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x754FC4L), "building_cagest", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x754E9CL), "building_chainst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x755464L), "building_chairst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x755B54L), "building_channelst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x7541F0L), "building_civzonest", "vtable_buildingst", toAddr(0x753194L));
applyVmethodTypes(toAddr(0x7556B4L), "building_coffinst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x75455CL), "building_doorst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x755C7CL), "building_farmplotst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x7547ACL), "building_floodgatest", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x755ECCL), "building_furnacest", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x75636CL), "building_roadst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x75558CL), "building_shopst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x7550ECL), "building_siegeenginest", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x755904L), "building_statuest", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x7540D4L), "building_stockpilest", "vtable_buildingst", toAddr(0x753194L));
applyVmethodTypes(toAddr(0x754B24L), "building_supportst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x75533CL), "building_tablest", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x75611CL), "building_tradedepotst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x7549FCL), "building_trapst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x756244L), "building_wagonst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x753938L), "building_weaponrackst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x754C4CL), "building_weaponst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x7557DCL), "building_wellst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x755A2CL), "building_windowst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x755FF4L), "building_workshopst", "vtable_building_actualst", toAddr(0x753810L));
applyVmethodTypes(toAddr(0x753194L), "buildingst", "vtable_buildingst", null);
applyVmethodTypes(toAddr(0x7658B4L), "general_ref_artifactst", "vtable_general_refst", toAddr(0x75A5DCL));
applyVmethodTypes(toAddr(0x765FECL), "general_ref_building_cagedst", "vtable_general_refst", toAddr(0x7660C8L));
applyVmethodTypes(toAddr(0x766018L), "general_ref_building_chainst", "vtable_general_refst", toAddr(0x7660C8L));
applyVmethodTypes(toAddr(0x76609CL), "general_ref_building_civzone_assignedst", "vtable_general_refst", toAddr(0x7660C8L));
applyVmethodTypes(toAddr(0x765F94L), "general_ref_building_holderst", "vtable_general_refst", toAddr(0x7660C8L));
applyVmethodTypes(toAddr(0x766070L), "general_ref_building_triggerst", "vtable_general_refst", toAddr(0x7660C8L));
applyVmethodTypes(toAddr(0x766044L), "general_ref_building_triggertargetst", "vtable_general_refst", toAddr(0x7660C8L));
applyVmethodTypes(toAddr(0x765FC0L), "general_ref_building_channeledst", "vtable_general_refst", toAddr(0x7660C8L));
applyVmethodTypes(toAddr(0x7660C8L), "general_ref_buildingst", "vtable_general_refst", toAddr(0x75A5DCL));
applyVmethodTypes(toAddr(0x75D4BCL), "general_ref_coinbatchst", "vtable_general_refst", toAddr(0x75A5DCL));
applyVmethodTypes(toAddr(0x76614CL), "general_ref_contained_in_itemst", "vtable_general_refst", toAddr(0x766254L));
applyVmethodTypes(toAddr(0x766228L), "general_ref_contains_itemst", "vtable_general_refst", toAddr(0x766254L));
applyVmethodTypes(toAddr(0x766280L), "general_ref_contains_unitst", "vtable_general_refst", toAddr(0x7662ACL));
applyVmethodTypes(toAddr(0x75A5B0L), "general_ref_entity_art_imagest", "vtable_general_refst", toAddr(0x75A5DCL));
applyVmethodTypes(toAddr(0x765888L), "general_ref_item_typest", "vtable_general_refst", toAddr(0x75A5DCL));
applyVmethodTypes(toAddr(0x766254L), "general_ref_itemst", "vtable_general_refst", toAddr(0x75A5DCL));
applyVmethodTypes(toAddr(0x7658E0L), "general_ref_mapsquarest", "vtable_general_refst", toAddr(0x75A5DCL));
applyVmethodTypes(toAddr(0x7661FCL), "general_ref_projectilest", "vtable_general_refst", toAddr(0x75A5DCL));
applyVmethodTypes(toAddr(0x766120L), "general_ref_unit_holderst", "vtable_general_refst", toAddr(0x7662ACL));
applyVmethodTypes(toAddr(0x7661A4L), "general_ref_unit_itemownerst", "vtable_general_refst", toAddr(0x7662ACL));
applyVmethodTypes(toAddr(0x766178L), "general_ref_unit_tradebringerst", "vtable_general_refst", toAddr(0x7662ACL));
applyVmethodTypes(toAddr(0x7661D0L), "general_ref_unit_traineest", "vtable_general_refst", toAddr(0x7662ACL));
applyVmethodTypes(toAddr(0x7660F4L), "general_ref_unit_workerst", "vtable_general_refst", toAddr(0x7662ACL));
applyVmethodTypes(toAddr(0x7662ACL), "general_ref_unitst", "vtable_general_refst", toAddr(0x75A5DCL));
applyVmethodTypes(toAddr(0x75A5DCL), "general_refst", "vtable_general_refst", null);
applyVmethodTypes(toAddr(0x75C8ECL), "history_event_add_hf_entity_linkst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C640L), "history_event_agreements_voidedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C008L), "history_event_artifact_createdst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75CABCL), "history_event_artifact_droppedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C9D4L), "history_event_artifact_foundst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75874CL), "history_event_artifact_hiddenst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C22CL), "history_event_artifact_lostst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x7587C0L), "history_event_artifact_possessedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75CA48L), "history_event_artifact_recoveredst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C804L), "history_event_created_sitest", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75CB30L), "history_event_demon_encasedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75CBA4L), "history_event_demon_releasedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C5CCL), "history_event_diplomat_lostst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C558L), "history_event_first_contact_failedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C2A0L), "history_event_first_contactst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x7589D0L), "history_event_hf_destroyed_sitest", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x7588C0L), "history_event_hist_figure_diedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C960L), "history_event_merchantst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C878L), "history_event_reclaim_sitest", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x758AB8L), "history_event_site_abandonedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x758A44L), "history_event_site_diedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C314L), "history_event_topicagreement_concludedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C3FCL), "history_event_topicagreement_madest", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C388L), "history_event_topicagreement_rejectedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C790L), "history_event_war_attacked_sitest", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75895CL), "history_event_war_destroyed_sitest", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C470L), "history_event_war_peace_acceptedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C4E4L), "history_event_war_peace_rejectedst", "vtable_history_eventst", toAddr(0x75C71CL));
applyVmethodTypes(toAddr(0x75C71CL), "history_eventst", "vtable_history_eventst", null);
applyVmethodTypes(toAddr(0x758934L), "interface_button_building_category_selectorst", "vtable_interface_buttonst", toAddr(0x75CCC0L));
applyVmethodTypes(toAddr(0x758948L), "interface_button_building_material_selectorst", "vtable_interface_buttonst", toAddr(0x75CCC0L));
applyVmethodTypes(toAddr(0x758B40L), "interface_button_building_new_jobst", "vtable_interface_buttonst", toAddr(0x75CCC0L));
applyVmethodTypes(toAddr(0x758BA4L), "interface_button_building_permit_foreign_armorst", "vtable_interface_buttonst", toAddr(0x75CCC0L));
applyVmethodTypes(toAddr(0x758B7CL), "interface_button_building_permit_foreign_siegeammost", "vtable_interface_buttonst", toAddr(0x75CCC0L));
applyVmethodTypes(toAddr(0x758B68L), "interface_button_building_permit_foreign_weaponst", "vtable_interface_buttonst", toAddr(0x75CCC0L));
applyVmethodTypes(toAddr(0x758B90L), "interface_button_building_permit_itemst", "vtable_interface_buttonst", toAddr(0x75CCC0L));
applyVmethodTypes(toAddr(0x758B54L), "interface_button_building_permit_trapcompst", "vtable_interface_buttonst", toAddr(0x75CCC0L));
applyVmethodTypes(toAddr(0x75CCC0L), "interface_button_buildingst", "vtable_interface_buttonst", toAddr(0x758B2CL));
applyVmethodTypes(toAddr(0x75CE54L), "interface_button_button_designate_selectst", "vtable_interface_buttonst", toAddr(0x75CCE8L));
applyVmethodTypes(toAddr(0x75CE68L), "interface_button_button_donest", "vtable_interface_buttonst", toAddr(0x75CCE8L));
applyVmethodTypes(toAddr(0x75CE04L), "interface_button_button_light_up_selectorst", "vtable_interface_buttonst", toAddr(0x75CCE8L));
applyVmethodTypes(toAddr(0x75CCE8L), "interface_button_buttonst", "vtable_interface_buttonst", toAddr(0x758B2CL));
applyVmethodTypes(toAddr(0x75CE2CL), "interface_button_construction_building_selectorst", "vtable_interface_buttonst", toAddr(0x75CCD4L));
applyVmethodTypes(toAddr(0x75CE18L), "interface_button_construction_category_selectorst", "vtable_interface_buttonst", toAddr(0x75CCD4L));
applyVmethodTypes(toAddr(0x75CE40L), "interface_button_construction_donest", "vtable_interface_buttonst", toAddr(0x75CCD4L));
applyVmethodTypes(toAddr(0x75CCD4L), "interface_button_constructionst", "vtable_interface_buttonst", toAddr(0x758B2CL));
applyVmethodTypes(toAddr(0x758B2CL), "interface_buttonst", "vtable_interface_buttonst", null);
applyVmethodTypes(toAddr(0x753580L), "item_actualst", "vtable_item_actualst", toAddr(0x75CE7CL));
applyVmethodTypes(toAddr(0x758EA0L), "item_ammost", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x763400L), "item_amuletst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x761F80L), "item_animaltrapst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x7645F0L), "item_anvilst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x759130L), "item_armorst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x7629C0L), "item_armorstandst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x7584A4L), "item_backpackst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x760350L), "item_ballistaarrowheadst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x764DA0L), "item_ballistapartsst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75A090L), "item_barrelst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75D530L), "item_barst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x75A898L), "item_bedst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x762730L), "item_binst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75DA50L), "item_blocksst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x75BAE8L), "item_bonesst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x758214L), "item_boxst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x7640D0L), "item_braceletst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x761CF0L), "item_bucketst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x762EE0L), "item_cabinetst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x761A60L), "item_cagest", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x764B10L), "item_catapultpartsst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x760D90L), "item_chainst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75AB28L), "item_chairst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x7605E0L), "item_cheesest", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x760870L), "item_clothst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x762210L), "item_coffinst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x757024L), "item_coinst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75A608L), "item_constructedst", "vtable_item_actualst", toAddr(0x757A64L));
applyVmethodTypes(toAddr(0x75F3F0L), "item_corpsepiecest", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x75B338L), "item_corpsest", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x757A64L), "item_craftedst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x765B9CL), "item_critterst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x763920L), "item_crownst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x7577D4L), "item_doorst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75EED0L), "item_drinkst", "vtable_item_actualst", toAddr(0x756AECL));
applyVmethodTypes(toAddr(0x763E40L), "item_earringst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75E9B0L), "item_extractst", "vtable_item_actualst", toAddr(0x756AECL));
applyVmethodTypes(toAddr(0x763170L), "item_figurinest", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75F680L), "item_fish_rawst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x757F84L), "item_fishst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x7572B4L), "item_flaskst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x760B00L), "item_floodgatest", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75D228L), "item_foodst", "vtable_item_actualst", toAddr(0x757A64L));
applyVmethodTypes(toAddr(0x764360L), "item_gemst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75685CL), "item_globst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x759B70L), "item_glovesst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x761020L), "item_gobletst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x759E00L), "item_helmst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x7612B0L), "item_instrumentst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x7600C0L), "item_leavesst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x7565CCL), "item_liquid_miscst", "vtable_item_actualst", toAddr(0x756AECL));
applyVmethodTypes(toAddr(0x756AECL), "item_liquidst", "vtable_item_actualst", toAddr(0x76590CL));
applyVmethodTypes(toAddr(0x76590CL), "item_liquipowderst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x757CF4L), "item_meatst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x75DCE0L), "item_orest", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x7598E0L), "item_pantsst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75F910L), "item_petst", "vtable_item_actualst", toAddr(0x765B9CL));
applyVmethodTypes(toAddr(0x753E18L), "item_plantst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x75EC40L), "item_potionst", "vtable_item_actualst", toAddr(0x756AECL));
applyVmethodTypes(toAddr(0x75F160L), "item_powder_organicst", "vtable_item_actualst", toAddr(0x75B048L));
applyVmethodTypes(toAddr(0x75B048L), "item_powderst", "vtable_item_actualst", toAddr(0x76590CL));
applyVmethodTypes(toAddr(0x75A320L), "item_quiverst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x753B88L), "item_remainsst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x763BB0L), "item_ringst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75E490L), "item_rockst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x75DF70L), "item_roughst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x75ADB8L), "item_sandst", "vtable_item_actualst", toAddr(0x75B048L));
applyVmethodTypes(toAddr(0x763690L), "item_scepterst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75B5C8L), "item_seedsst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x75FE30L), "item_shellst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x759650L), "item_shieldst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x7593C0L), "item_shoesst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x765030L), "item_siegeammost", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75B858L), "item_skin_rawst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x75FBA0L), "item_skin_tannedst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x75BD78L), "item_skullst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x75D7C0L), "item_smallgemst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x7624A0L), "item_statuest", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75E200L), "item_stonest", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x757544L), "item_tablest", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x756D7CL), "item_threadst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x764880L), "item_totemst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x761540L), "item_toyst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x765550L), "item_trapcompst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x7652C0L), "item_trappartsst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x7532B0L), "item_verminst", "vtable_item_actualst", toAddr(0x765B9CL));
applyVmethodTypes(toAddr(0x762C50L), "item_weaponrackst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x758C10L), "item_weaponst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x7617D0L), "item_windowst", "vtable_item_actualst", toAddr(0x75A608L));
applyVmethodTypes(toAddr(0x75E720L), "item_woodst", "vtable_item_actualst", toAddr(0x753580L));
applyVmethodTypes(toAddr(0x765828L), "itemdef_ammost", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x76581CL), "itemdef_armorst", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x76587CL), "itemdef_foodst", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x765840L), "itemdef_glovesst", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x765864L), "itemdef_helmst", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x765810L), "itemdef_instrumentst", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x765870L), "itemdef_pantsst", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x765858L), "itemdef_shieldst", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x76584CL), "itemdef_shoesst", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x765834L), "itemdef_siegeammost", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x765804L), "itemdef_toyst", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x7657F8L), "itemdef_trapcompst", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x7657ECL), "itemdef_weaponst", "vtable_itemdefst", toAddr(0x7657E0L));
applyVmethodTypes(toAddr(0x7657E0L), "itemdefst", "vtable_itemdefst", null);
applyVmethodTypes(toAddr(0x75D204L), "itemimprovement_art_imagest", "vtable_itemimprovementst", toAddr(0x75D4E8L));
applyVmethodTypes(toAddr(0x75D198L), "itemimprovement_bandsst", "vtable_itemimprovementst", toAddr(0x75D4E8L));
applyVmethodTypes(toAddr(0x75D108L), "itemimprovement_clothst", "vtable_itemimprovementst", toAddr(0x75D4E8L));
applyVmethodTypes(toAddr(0x75D1E0L), "itemimprovement_coveredst", "vtable_itemimprovementst", toAddr(0x75D4E8L));
applyVmethodTypes(toAddr(0x75D150L), "itemimprovement_itemspecificst", "vtable_itemimprovementst", toAddr(0x75D4E8L));
applyVmethodTypes(toAddr(0x75D1BCL), "itemimprovement_rings_hangingst", "vtable_itemimprovementst", toAddr(0x75D4E8L));
applyVmethodTypes(toAddr(0x75D50CL), "itemimprovement_sewn_imagest", "vtable_itemimprovementst", toAddr(0x75D4E8L));
applyVmethodTypes(toAddr(0x75D174L), "itemimprovement_spikesst", "vtable_itemimprovementst", toAddr(0x75D4E8L));
applyVmethodTypes(toAddr(0x75D12CL), "itemimprovement_threadst", "vtable_itemimprovementst", toAddr(0x75D4E8L));
applyVmethodTypes(toAddr(0x75D4E8L), "itemimprovementst", "vtable_itemimprovementst", null);
applyVmethodTypes(toAddr(0x75CE7CL), "itemst", "vtable_itemst", null);
applyVmethodTypes(toAddr(0x75CCFCL), "layer_object_buttonst", "vtable_layer_objectst", null);
applyVmethodTypes(toAddr(0x75CD40L), "layer_object_listst", "vtable_layer_objectst", null);
applyVmethodTypes(toAddr(0x753540L), "proj_itemst", "vtable_projst", toAddr(0x7540B8L));
applyVmethodTypes(toAddr(0x765F78L), "proj_magicst", "vtable_projst", toAddr(0x7540B8L));
applyVmethodTypes(toAddr(0x756494L), "proj_unitst", "vtable_projst", toAddr(0x7540B8L));
applyVmethodTypes(toAddr(0x7540B8L), "projst", "vtable_projst", null);
applyVmethodTypes(toAddr(0x766350L), "script_step_conditionalst", "vtable_script_stepst", toAddr(0x766338L));
applyVmethodTypes(toAddr(0x7662F8L), "script_step_constructtopiclistst", "vtable_script_stepst", toAddr(0x766338L));
applyVmethodTypes(toAddr(0x766390L), "script_step_dipeventst", "vtable_script_stepst", toAddr(0x7662E8L));
applyVmethodTypes(toAddr(0x766328L), "script_step_diphistoryst", "vtable_script_stepst", toAddr(0x766338L));
applyVmethodTypes(toAddr(0x766318L), "script_step_discussst", "vtable_script_stepst", toAddr(0x766338L));
applyVmethodTypes(toAddr(0x7662D8L), "script_step_invasionst", "vtable_script_stepst", toAddr(0x7662E8L));
applyVmethodTypes(toAddr(0x766370L), "script_step_setvarst", "vtable_script_stepst", toAddr(0x766338L));
applyVmethodTypes(toAddr(0x766360L), "script_step_simpleactionst", "vtable_script_stepst", toAddr(0x766338L));
applyVmethodTypes(toAddr(0x766380L), "script_step_textviewerst", "vtable_script_stepst", toAddr(0x766338L));
applyVmethodTypes(toAddr(0x766308L), "script_step_topicdiscussionst", "vtable_script_stepst", toAddr(0x766338L));
applyVmethodTypes(toAddr(0x7662E8L), "script_step_eventst", "vtable_script_stepst", toAddr(0x766338L));
applyVmethodTypes(toAddr(0x766338L), "script_stepst", "vtable_script_stepst", null);
applyVmethodTypes(toAddr(0x76634CL), "script_var_longst", "vtable_script_varst", null);
applyVmethodTypes(toAddr(0x766348L), "script_var_unitst", "vtable_script_varst", null);
applyVmethodTypes(toAddr(0x7564C8L), "task_kill_nemesisst", "vtable_taskst", toAddr(0x7564E8L));
applyVmethodTypes(toAddr(0x7564E8L), "taskst", "vtable_taskst", null);
applyVmethodTypes(toAddr(0x758BFCL), "text_info_element_longst", "vtable_text_info_elementst", toAddr(0x758BF0L));
applyVmethodTypes(toAddr(0x758BE4L), "text_info_element_stringst", "vtable_text_info_elementst", toAddr(0x758BF0L));
applyVmethodTypes(toAddr(0x758BF0L), "text_info_elementst", "vtable_text_info_elementst", null);
applyVmethodTypes(toAddr(0x7663B8L), "vegst", "vtable_vegst", null);
applyVmethodTypes(toAddr(0x75659CL), "viewscreen_adventure_logst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x756524L), "viewscreen_adventure_travelst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C07CL), "viewscreen_announcelistst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x765E2CL), "viewscreen_assigntradest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x765E5CL), "viewscreen_barterst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C1E4L), "viewscreen_buildinglistst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C6E4L), "viewscreen_buildingst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C184L), "viewscreen_civlistst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C1B4L), "viewscreen_commandchainst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x7564B0L), "viewscreen_conversationst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C124L), "viewscreen_createquotast", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75CC78L), "viewscreen_customize_unitst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x756584L), "viewscreen_dungeon_announcest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75656CL), "viewscreen_dungeon_monsterstatusst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x7565B4L), "viewscreen_dungeon_wrestlest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x756554L), "viewscreen_dungeonmodest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x758734L), "viewscreen_dwarfmodest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C16CL), "viewscreen_entityst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75B2D8L), "viewscreen_export_regionst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C6CCL), "viewscreen_itemst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C10CL), "viewscreen_jobmanagementst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C6FCL), "viewscreen_jobst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C0DCL), "viewscreen_justicest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75CC48L), "viewscreen_keybindingsst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C094L), "viewscreen_kitchenprefst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75CD84L), "viewscreen_layer_stockpilest", "vtable_viewscreenst", toAddr(0x75CD9CL));
applyVmethodTypes(toAddr(0x75CDB4L), "viewscreen_layer_workshop_profilest", "vtable_viewscreenst", toAddr(0x75CD9CL));
applyVmethodTypes(toAddr(0x75CD9CL), "viewscreen_layerst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75B308L), "viewscreen_legendsst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75CCA8L), "viewscreen_loadgamest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x765E8CL), "viewscreen_meetingst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75CC90L), "viewscreen_movieplayerst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75B2F0L), "viewscreen_new_regionst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C1FCL), "viewscreen_noblelistst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C214L), "viewscreen_noblest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75CC18L), "viewscreen_optionst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C1CCL), "viewscreen_overallstatusst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C0ACL), "viewscreen_petst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C0C4L), "viewscreen_pricest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x765F04L), "viewscreen_requestagreementst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75CC30L), "viewscreen_savegamest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x758834L), "viewscreen_selectitemst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75700CL), "viewscreen_setupadventurest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x7663A0L), "viewscreen_setupdwarfgamest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C19CL), "viewscreen_squadst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C6B4L), "viewscreen_storesst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x765F1CL), "viewscreen_textviewerst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75B320L), "viewscreen_titlest", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x765EBCL), "viewscreen_topicmeeting_takerequests_dwarfst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x765ED4L), "viewscreen_topicmeeting_takerequests_humanst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x765EA4L), "viewscreen_topicmeetingst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x765EECL), "viewscreen_tradeagreementst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x765E74L), "viewscreen_tradegoodsst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x765E44L), "viewscreen_tradelistst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C154L), "viewscreen_treasurelistst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C13CL), "viewscreen_unitjobsst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75CC60L), "viewscreen_unitst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75C0F4L), "viewscreen_wagesst", "vtable_viewscreenst", toAddr(0x75653CL));
applyVmethodTypes(toAddr(0x75653CL), "viewscreenst", "vtable_viewscreenst", null);
}
    protected void run() throws Exception {
        manager = currentProgram.getDataTypeManager();
        Function fn = getFunction("_guard_check_icall");
        vmeth_nullptr = (fn != null) ? fn.getEntryPoint() : toAddr(0);
globals();
vtables();
vmethods();
    }
}
